run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gofmt
    - goimports
    - revive
    - misspell
    - prealloc
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - dupl
        - gosec

# output configuration options
output:
  # format: colored-line-number
  print-issued-lines: true
  print-linter-name: true